### ISSUE TITLE
通过mamba env create -f environment-cuda.yaml创建环境后 pip install -e .出现错误

### ISSUE THREAD

**Issue by yutchina** [sablin39/iGibson-imitation#1]
通过mamba env create -f environment-cuda.yaml创建环境后 pip install -e .出现错误

<img width="1045" alt="1732209656060" src="https://github.com/user-attachments/assets/5500576e-83af-47ec-90b9-bbfebff0c5d1">

**Comment by sablin39** [comment]
@yutchina 请提供更详细的报错结果。目前environment.yaml 已经更新，可以更新后再尝试一下。
